### ISSUE TITLE
Dynmap MultiServer does not start if a server is offline

### ISSUE THREAD

**Issue by Feld0** [Cube-Space/Dynmap-Multiserver#5]
Dynmap MultiServer won't start if it can't find the JSON config file in a map directory, which only exists while a server is running.

In a nontrivial Bungeecord network, this is problematic as the entire collection of maps behind Dynmap MultiServer is inaccessible if Dynmap MultiServer gets restarted while one of the Minecraft servers is offline.

**Comment by geNAZt** [comment]
Stacktrace or complete Logoutput?

**Comment by Feld0** [comment]
@geNAZt Nevermind this issue - this turned out to be a problem on my end.
